### ISSUE TITLE
Broken after update to IOS 17.4.1

### ISSUE THREAD

**Issue by Ben10UltimateAlien** [metanote-dev/metanote-dev.github.io#5]
After updating to IOS 17.4.1 the app started buggin as in not showing agenda events and not even being able to open the files, and that is when the app even opens, often it just is unresponsive and returns to home screen after opening.

**Comment by metanote-dev** [comment]
It seems like after iOS upgrade, Metanote lost access permissions to external folders, resulting in a series of issues. Have you added some external folders? If the problem is related to external folder permissions, you can remove the external folders from Metanote or try reinstalling Metanote, and then add them again. Please note that uninstalling Metanote will not delete files in external folders, but it will delete files in Metanote's internal Documents folder. Therefore, if you have files here, make sure to move them to external folders before uninstalling. If the issue persists, please contact me.

**Comment by metanote-dev** [comment]
This does seem quite strange. Does the black screen appear every time? We haven't received any user feedback about similar issues. In my testing, I've occasionally encountered a black screen on the first launch after a fresh installation, but killing the app and relaunching it resolves the issue. I'm still investigating the cause of this problem. Please try killing the app and restarting it if you encounter the black screen again. I'll also try to replicate this issue on iOS 17.4.1 as much as possible.

**Comment by metanote-dev** [comment]
I just attempted testing on iOS 17.4.1, but I found that Apple hasn't released a simulator for iOS 17.4.1. I suspect that Apple may have changed some permissions related to accessing external folders in iOS 17.4.1. If the issue persists, please contact me to obtain the beta version. Since I don't have a testing environment for iOS 17.4.1, I will try to address the file access permission-related issues in the beta version. I will do my best to resolve this problem.

**Comment by Ben10UltimateAlien** [comment]
The black screen is only an issue after changing the file settings to source from local directories. If I don't use external folders the app works as it did before the update. I have tested unninstalling and reinstalling several times to check and it only stops working after sourcing from external folders, so that is probably where the issue lies. Thank you for efforts.
